export const INCREMENT_VALUE = 'INCREMENT_VALUE';
export const DECREMENT_VALUE = 'DECREMENT_VALUE';
export const SET_VALUE = 'SET_VALUE';
export const EXEC_LS_SUCCESS = 'EXEC_LS_SUCCESS';
export const EXEC_LS_ERROR = 'EXEC_LS_ERROR';
